excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jorgeboucas.github.io
title: Jorge Boucas
email: mail@jorgeboucas.com
author: Jorge Boucas
description: Not much to put here..
paginate: 4
google_analytics: 
